version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "testdb"
    command: postgres -c 'max_connections=10'
    ports:
      - 5432:5432